class AddDataToAutomodels < ActiveRecord::Migration
  def self.up
		Automodels.create(:make => "Acura", :model => "CL")
		Automodels.create(:make => "Acura", :model => "MDX")
		Automodels.create(:make => "Acura", :model => "RDX")
		Automodels.create(:make => "Acura", :model => "RL")
		Automodels.create(:make => "Acura", :model => "RSX")
		Automodels.create(:make => "Acura", :model => "SLX")
		Automodels.create(:make => "Acura", :model => "TL")
		Automodels.create(:make => "Acura", :model => "TSX")
		Automodels.create(:make => "Acura", :model => "Integra")
		Automodels.create(:make => "Acura", :model => "Legend")
		Automodels.create(:make => "Acura", :model => "NSX")
		Automodels.create(:make => "Acura", :model => "Vigor")
		Automodels.create(:make => "Aston Martin", :model => "DB7")
		Automodels.create(:make => "Aston Martin", :model => "DB7 Vantage")
		Automodels.create(:make => "Aston Martin", :model => "DB9")
		Automodels.create(:make => "Aston Martin", :model => "DBS")
		Automodels.create(:make => "Aston Martin", :model => "Vanquish")
		Automodels.create(:make => "Aston Martin", :model => "Vanquish S")
		Automodels.create(:make => "Aston Martin", :model => "Vantage")
		Automodels.create(:make => "Audi", :model => "A3")
		Automodels.create(:make => "Audi", :model => "A4")
		Automodels.create(:make => "Audi", :model => "A5")
		Automodels.create(:make => "Audi", :model => "A6")
		Automodels.create(:make => "Audi", :model => "A8")
		Automodels.create(:make => "Audi", :model => "A8 L")
		Automodels.create(:make => "Audi", :model => "allroad")
		Automodels.create(:make => "Audi", :model => "Cabriolet")
		Automodels.create(:make => "Audi", :model => "Q5")
		Automodels.create(:make => "Audi", :model => "Q7")
		Automodels.create(:make => "Audi", :model => "R8")
		Automodels.create(:make => "Audi", :model => "RS4")
		Automodels.create(:make => "Audi", :model => "RS6")
		Automodels.create(:make => "Audi", :model => "S4")
		Automodels.create(:make => "Audi", :model => "S5")
		Automodels.create(:make => "Audi", :model => "S6")
		Automodels.create(:make => "Audi", :model => "S8")
		Automodels.create(:make => "Audi", :model => "TT")
		Automodels.create(:make => "Audi", :model => "TTS")
		Automodels.create(:make => "Bentley", :model => "Arnage")
		Automodels.create(:make => "Bentley", :model => "Azure")
		Automodels.create(:make => "Bentley", :model => "Brooklands")
		Automodels.create(:make => "Bentley", :model => "Continental")
		Automodels.create(:make => "Bentley", :model => "Continental Flying Spur")
		Automodels.create(:make => "Bentley", :model => "Continental GT")
		Automodels.create(:make => "BMW", :model => "1-Series")
		Automodels.create(:make => "BMW", :model => "3-Series")
		Automodels.create(:make => "BMW", :model => "5-Series")
		Automodels.create(:make => "BMW", :model => "6-Series")
		Automodels.create(:make => "BMW", :model => "7-Series")
		Automodels.create(:make => "BMW", :model => "8-Series")
		Automodels.create(:make => "BMW", :model => "M3")
		Automodels.create(:make => "BMW", :model => "M5")
		Automodels.create(:make => "BMW", :model => "M6")
		Automodels.create(:make => "BMW", :model => "X3-Series")
		Automodels.create(:make => "BMW", :model => "X5-Series")
		Automodels.create(:make => "BMW", :model => "X6-Series")
		Automodels.create(:make => "BMW", :model => "Z3-Series")
		Automodels.create(:make => "BMW", :model => "Z4")
		Automodels.create(:make => "BMW", :model => "Z8-Series")
		Automodels.create(:make => "Buick", :model => "Century")
		Automodels.create(:make => "Buick", :model => "Enclave")
		Automodels.create(:make => "Buick", :model => "LaCrosse")
		Automodels.create(:make => "Buick", :model => "LeSabre")
		Automodels.create(:make => "Buick", :model => "Lucerne")
		Automodels.create(:make => "Buick", :model => "Park Avenue")
		Automodels.create(:make => "Buick", :model => "Rainier")
		Automodels.create(:make => "Buick", :model => "Regal")
		Automodels.create(:make => "Buick", :model => "Rendezvous")
		Automodels.create(:make => "Buick", :model => "Riviera")
		Automodels.create(:make => "Buick", :model => "Skylark")
		Automodels.create(:make => "Buick", :model => "Terraza")
		Automodels.create(:make => "Cadillac", :model => "Catera")
		Automodels.create(:make => "Cadillac", :model => "Concours")
		Automodels.create(:make => "Cadillac", :model => "CTS")
		Automodels.create(:make => "Cadillac", :model => "d'Elegance")
		Automodels.create(:make => "Cadillac", :model => "DeVille")
		Automodels.create(:make => "Cadillac", :model => "DeVille DHS")
		Automodels.create(:make => "Cadillac", :model => "DeVille DTS")
		Automodels.create(:make => "Cadillac", :model => "DTS")
		Automodels.create(:make => "Cadillac", :model => "DTS Professional")
		Automodels.create(:make => "Cadillac", :model => "Eldorado")
		Automodels.create(:make => "Cadillac", :model => "Escalade")
		Automodels.create(:make => "Cadillac", :model => "Escalade ESV")
		Automodels.create(:make => "Cadillac", :model => "Escalade EXT")
		Automodels.create(:make => "Cadillac", :model => "Escalade Hybrid")
		Automodels.create(:make => "Cadillac", :model => "Seville")
		Automodels.create(:make => "Cadillac", :model => "SRX")
		Automodels.create(:make => "Cadillac", :model => "STS")
		Automodels.create(:make => "Cadillac", :model => "V-Series")
		Automodels.create(:make => "Cadillac", :model => "XLR")
		Automodels.create(:make => "Chevrolet", :model => "Astro Cargo Van")
		Automodels.create(:make => "Chevrolet", :model => "Astro Passenger")
		Automodels.create(:make => "Chevrolet", :model => "Avalanche")
		Automodels.create(:make => "Chevrolet", :model => "Aveo")
		Automodels.create(:make => "Chevrolet", :model => "Blazer")
		Automodels.create(:make => "Chevrolet", :model => "C 3500 HD")
		Automodels.create(:make => "Chevrolet", :model => "C/K 1500")
		Automodels.create(:make => "Chevrolet", :model => "C/K 1500 Work")
		Automodels.create(:make => "Chevrolet", :model => "C/K 2500")
		Automodels.create(:make => "Chevrolet", :model => "C/K 3500")
		Automodels.create(:make => "Chevrolet", :model => "C/K 3500 Crew Cab")
		Automodels.create(:make => "Chevrolet", :model => "Camaro")
		Automodels.create(:make => "Chevrolet", :model => "Cavalier")
		Automodels.create(:make => "Chevrolet", :model => "Chevy Cargo Van")
		Automodels.create(:make => "Chevrolet", :model => "Classic")
		Automodels.create(:make => "Chevrolet", :model => "Cobalt")
		Automodels.create(:make => "Chevrolet", :model => "Colorado")
		Automodels.create(:make => "Chevrolet", :model => "Corvette")
		Automodels.create(:make => "Chevrolet", :model => "Equinox")
		Automodels.create(:make => "Chevrolet", :model => "HHR")
		Automodels.create(:make => "Chevrolet", :model => "Impala")
		Automodels.create(:make => "Chevrolet", :model => "Lumina")
		Automodels.create(:make => "Chevrolet", :model => "Malibu")
		Automodels.create(:make => "Chevrolet", :model => "Malibu Classic")
		Automodels.create(:make => "Chevrolet", :model => "Malibu Hybrid")
		Automodels.create(:make => "Chevrolet", :model => "Malibu Maxx")
		Automodels.create(:make => "Chevrolet", :model => "Metro")
		Automodels.create(:make => "Chevrolet", :model => "Monte Carlo")
		Automodels.create(:make => "Chevrolet", :model => "New Tahoe")
		Automodels.create(:make => "Chevrolet", :model => "Prizm")
		Automodels.create(:make => "Chevrolet", :model => "S-10")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 1500")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 1500 Classic")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 1500 Classic Hybrid")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 1500 Hybrid")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 1500HD")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 1500HD Classic")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 2500")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 2500HD")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 2500HD Classic")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 3500")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 3500 Classic")
		Automodels.create(:make => "Chevrolet", :model => "Silverado 3500HD")
		Automodels.create(:make => "Chevrolet", :model => "Silverado SS")
		Automodels.create(:make => "Chevrolet", :model => "Silverado SS Classic")
		Automodels.create(:make => "Chevrolet", :model => "SSR")
		Automodels.create(:make => "Chevrolet", :model => "Suburban")
		Automodels.create(:make => "Chevrolet", :model => "Tahoe")
		Automodels.create(:make => "Chevrolet", :model => "Tahoe Hybrid")
		Automodels.create(:make => "Chevrolet", :model => "Tracker")
		Automodels.create(:make => "Chevrolet", :model => "Trailblazer")
		Automodels.create(:make => "Chevrolet", :model => "Traverse")
		Automodels.create(:make => "Chevrolet", :model => "Uplander")
		Automodels.create(:make => "Chevrolet", :model => "Uplander Cargo Van")
		Automodels.create(:make => "Chevrolet", :model => "Venture")
		Automodels.create(:make => "Chevrolet", :model => "Venture Cargo Van")
		Automodels.create(:make => "Chrysler", :model => "300M")
		Automodels.create(:make => "Chrysler", :model => "300-Series")
		Automodels.create(:make => "Chrysler", :model => "Aspen")
		Automodels.create(:make => "Chrysler", :model => "Cirrus")
		Automodels.create(:make => "Chrysler", :model => "Concorde")
		Automodels.create(:make => "Chrysler", :model => "Crossfire")
		Automodels.create(:make => "Chrysler", :model => "LHS")
		Automodels.create(:make => "Chrysler", :model => "Pacifica")
		Automodels.create(:make => "Chrysler", :model => "Prowler")
		Automodels.create(:make => "Chrysler", :model => "PT Cruiser")
		Automodels.create(:make => "Chrysler", :model => "Sebring")
		Automodels.create(:make => "Chrysler", :model => "Town & Country")
		Automodels.create(:make => "Chrysler", :model => "Voyager")
		Automodels.create(:make => "Daewoo", :model => "Lanos")
		Automodels.create(:make => "Daewoo", :model => "Leganza")
		Automodels.create(:make => "Daewoo", :model => "Nubira")
		Automodels.create(:make => "Dodge", :model => "Avenger")
		Automodels.create(:make => "Dodge", :model => "Caliber")
		Automodels.create(:make => "Dodge", :model => "Caravan")
		Automodels.create(:make => "Dodge", :model => "Caravan C/V")
		Automodels.create(:make => "Dodge", :model => "Challenger")
		Automodels.create(:make => "Dodge", :model => "Charger")
		Automodels.create(:make => "Dodge", :model => "Dakota")
		Automodels.create(:make => "Dodge", :model => "Durango")
		Automodels.create(:make => "Dodge", :model => "Grand Caravan")
		Automodels.create(:make => "Dodge", :model => "Grand Caravan C/V")
		Automodels.create(:make => "Dodge", :model => "Intrepid")
		Automodels.create(:make => "Dodge", :model => "Journey")
		Automodels.create(:make => "Dodge", :model => "Magnum")
		Automodels.create(:make => "Dodge", :model => "Neon")
		Automodels.create(:make => "Dodge", :model => "Nitro")
		Automodels.create(:make => "Dodge", :model => "Ram 1500")
		Automodels.create(:make => "Dodge", :model => "Ram 2500")
		Automodels.create(:make => "Dodge", :model => "Ram 3500")
		Automodels.create(:make => "Dodge", :model => "Ram 4500")
		Automodels.create(:make => "Dodge", :model => "Ram 5500")
		Automodels.create(:make => "Dodge", :model => "Ram BR2500")
		Automodels.create(:make => "Dodge", :model => "Ram BR2500 Chassis Cab")
		Automodels.create(:make => "Dodge", :model => "Ram BR3500")
		Automodels.create(:make => "Dodge", :model => "Ram SRT-10")
		Automodels.create(:make => "Dodge", :model => "Ram Van")
		Automodels.create(:make => "Dodge", :model => "Ram Wagon")
		Automodels.create(:make => "Dodge", :model => "Sprinter")
		Automodels.create(:make => "Dodge", :model => "Sprinter Wagon")
		Automodels.create(:make => "Dodge", :model => "Stratus")
		Automodels.create(:make => "Dodge", :model => "Stratus Coupe")
		Automodels.create(:make => "Dodge", :model => "Stratus Sedan")
		Automodels.create(:make => "Dodge", :model => "Viper")
		Automodels.create(:make => "Eagle", :model => "Talon")
		Automodels.create(:make => "Eagle", :model => "Vision")
		Automodels.create(:make => "Ferrari", :model => "360")
		Automodels.create(:make => "Ferrari", :model => "430")
		Automodels.create(:make => "Ferrari", :model => "456M")
		Automodels.create(:make => "Ferrari", :model => "575M Maranello")
		Automodels.create(:make => "Ferrari", :model => "599 GTB Fiorano")
		Automodels.create(:make => "Ferrari", :model => "612 Scaglietti")
		Automodels.create(:make => "Ferrari", :model => "Enzo")
		Automodels.create(:make => "Ford", :model => "Aerostar Cargo Van")
		Automodels.create(:make => "Ford", :model => "Aerostar Wagon")
		Automodels.create(:make => "Ford", :model => "Aspire")
		Automodels.create(:make => "Ford", :model => "Club Wagon")
		Automodels.create(:make => "Ford", :model => "Contour")
		Automodels.create(:make => "Ford", :model => "Crown Victoria")
		Automodels.create(:make => "Ford", :model => "Econoline Cargo Van")
		Automodels.create(:make => "Ford", :model => "Econoline Wagon")
		Automodels.create(:make => "Ford", :model => "Edge")
		Automodels.create(:make => "Ford", :model => "Escape")
		Automodels.create(:make => "Ford", :model => "Escort")
		Automodels.create(:make => "Ford", :model => "Excursion")
		Automodels.create(:make => "Ford", :model => "Expedition")
		Automodels.create(:make => "Ford", :model => "Expedition EL")
		Automodels.create(:make => "Ford", :model => "Explorer")
		Automodels.create(:make => "Ford", :model => "Explorer Sport")
		Automodels.create(:make => "Ford", :model => "Explorer Sport Trac")
		Automodels.create(:make => "Ford", :model => "F-150")
		Automodels.create(:make => "Ford", :model => "F-150 Heritage")
		Automodels.create(:make => "Ford", :model => "F-150 Standard")
		Automodels.create(:make => "Ford", :model => "F-150 Work Series")
		Automodels.create(:make => "Ford", :model => "F-250")
		Automodels.create(:make => "Ford", :model => "F-250 HD")
		Automodels.create(:make => "Ford", :model => "F-250 Standard")
		Automodels.create(:make => "Ford", :model => "F-250 Work Series")
		Automodels.create(:make => "Ford", :model => "F-350")
		Automodels.create(:make => "Ford", :model => "F-350 Chassis Cab")
		Automodels.create(:make => "Ford", :model => "F-800")
		Automodels.create(:make => "Ford", :model => "Five Hundred")
		Automodels.create(:make => "Ford", :model => "Flex")
		Automodels.create(:make => "Ford", :model => "Focus")
		Automodels.create(:make => "Ford", :model => "Freestar Cargo Van")
		Automodels.create(:make => "Ford", :model => "Freestar Wagon")
		Automodels.create(:make => "Ford", :model => "Freestyle")
		Automodels.create(:make => "Ford", :model => "F-Super Duty Chassis Cab")
		Automodels.create(:make => "Ford", :model => "Fusion")
		Automodels.create(:make => "Ford", :model => "GT")
		Automodels.create(:make => "Ford", :model => "Low Cab Forward")
		Automodels.create(:make => "Ford", :model => "Mustang")
		Automodels.create(:make => "Ford", :model => "Probe")
		Automodels.create(:make => "Ford", :model => "Ranger")
		Automodels.create(:make => "Ford", :model => "Super Duty E-350 DRW")
		Automodels.create(:make => "Ford", :model => "Super Duty E-450 DRW")
		Automodels.create(:make => "Ford", :model => "Super Duty E-550 DRW")
		Automodels.create(:make => "Ford", :model => "Super Duty F-250")
		Automodels.create(:make => "Ford", :model => "Super Duty F-350 DRW")
		Automodels.create(:make => "Ford", :model => "Super Duty F-350 SRW")
		Automodels.create(:make => "Ford", :model => "Super Duty F-450")
		Automodels.create(:make => "Ford", :model => "Super Duty F-450 DRW")
		Automodels.create(:make => "Ford", :model => "Super Duty F-550")
		Automodels.create(:make => "Ford", :model => "Super Duty F-550 DRW")
		Automodels.create(:make => "Ford", :model => "Super Duty F-650")
		Automodels.create(:make => "Ford", :model => "Super Duty F-650 Pro Loader")
		Automodels.create(:make => "Ford", :model => "Super Duty F-650 Straight Frame")
		Automodels.create(:make => "Ford", :model => "Super Duty F-750")
		Automodels.create(:make => "Ford", :model => "Super Duty F-750 Severe Service")
		Automodels.create(:make => "Ford", :model => "Super Duty F-750 Straight Frame")
		Automodels.create(:make => "Ford", :model => "Taurus")
		Automodels.create(:make => "Ford", :model => "Taurus X")
		Automodels.create(:make => "Ford", :model => "Thunderbird")
		Automodels.create(:make => "Ford", :model => "Windstar Cargo Van")
		Automodels.create(:make => "Ford", :model => "Windstar Wagon")
		Automodels.create(:make => "Ford", :model => "ZX2")
		Automodels.create(:make => "Geo", :model => "Metro")
		Automodels.create(:make => "Geo", :model => "Prizm")
		Automodels.create(:make => "Geo", :model => "Tracker")
		Automodels.create(:make => "GMC", :model => "Denali")
		Automodels.create(:make => "GMC", :model => "Acadia")
		Automodels.create(:make => "GMC", :model => "Canyon")
		Automodels.create(:make => "GMC", :model => "Classic Sierra 2500")
		Automodels.create(:make => "GMC", :model => "Classic Sierra 3500")
		Automodels.create(:make => "GMC", :model => "Classic Sierra 3500 HD")
		Automodels.create(:make => "GMC", :model => "Classic Sierra 3500 Crew Cab")
		Automodels.create(:make => "GMC", :model => "Envoy")
		Automodels.create(:make => "GMC", :model => "Envoy XL")
		Automodels.create(:make => "GMC", :model => "Envoy XUV")
		Automodels.create(:make => "GMC", :model => "Jimmy")
		Automodels.create(:make => "GMC", :model => "New Sierra 1500")
		Automodels.create(:make => "GMC", :model => "New Sierra 2500")
		Automodels.create(:make => "GMC", :model => "Safari Cargo Van")
		Automodels.create(:make => "GMC", :model => "Safari Passenger")
		Automodels.create(:make => "GMC", :model => "Savana Passenger")
		Automodels.create(:make => "GMC", :model => "Sierra 1500")
		Automodels.create(:make => "GMC", :model => "Sierra 1500 Classic")
		Automodels.create(:make => "GMC", :model => "Sierra 1500 Classic Hybrid")
		Automodels.create(:make => "GMC", :model => "Sierra 1500 Hybrid")
		Automodels.create(:make => "GMC", :model => "Sierra 1500 Special")
		Automodels.create(:make => "GMC", :model => "Sierra 1500HD")
		Automodels.create(:make => "GMC", :model => "Sierra 1500HD Classic")
		Automodels.create(:make => "GMC", :model => "Sierra 2500")
		Automodels.create(:make => "GMC", :model => "Sierra 2500HD")
		Automodels.create(:make => "GMC", :model => "Sierra 2500HD Classic")
		Automodels.create(:make => "GMC", :model => "Sierra 3500")
		Automodels.create(:make => "GMC", :model => "Sierra 3500 Classic")
		Automodels.create(:make => "GMC", :model => "Sierra 3500 Crew Cab")
		Automodels.create(:make => "GMC", :model => "Sierra 3500HD")
		Automodels.create(:make => "GMC", :model => "Sierra Denali")
		Automodels.create(:make => "GMC", :model => "Sierra Denali Classic")
		Automodels.create(:make => "GMC", :model => "Sonoma")
		Automodels.create(:make => "GMC", :model => "Suburban")
		Automodels.create(:make => "GMC", :model => "Terrain")
		Automodels.create(:make => "GMC", :model => "Yukon")
		Automodels.create(:make => "GMC", :model => "Yukon Denali")
		Automodels.create(:make => "GMC", :model => "Yukon Hybrid")
		Automodels.create(:make => "GMC", :model => "Yukon Hybrid Denali")
		Automodels.create(:make => "GMC", :model => "Yukon XL")
		Automodels.create(:make => "GMC", :model => "Yukon XL Denali")
		Automodels.create(:make => "Honda", :model => "Accord Coupe")
		Automodels.create(:make => "Honda", :model => "Accord Hybrid")
		Automodels.create(:make => "Honda", :model => "Accord Sedan")
		Automodels.create(:make => "Honda", :model => "Accord Wagon")
		Automodels.create(:make => "Honda", :model => "Civic Coupe")
		Automodels.create(:make => "Honda", :model => "Civic del Sol")
		Automodels.create(:make => "Honda", :model => "Civic GX NGV")
		Automodels.create(:make => "Honda", :model => "Civic Hatchback")
		Automodels.create(:make => "Honda", :model => "Civic Hybrid")
		Automodels.create(:make => "Honda", :model => "Civic Sedan")
		Automodels.create(:make => "Honda", :model => "Civic Si Coupe")
		Automodels.create(:make => "Honda", :model => "Civic Si Hatchback")
		Automodels.create(:make => "Honda", :model => "Civic Si Sedan")
		Automodels.create(:make => "Honda", :model => "CR-V")
		Automodels.create(:make => "Honda", :model => "Element")
		Automodels.create(:make => "Honda", :model => "Fit")
		Automodels.create(:make => "Honda", :model => "Insight")
		Automodels.create(:make => "Honda", :model => "Odyssey")
		Automodels.create(:make => "Honda", :model => "Passport")
		Automodels.create(:make => "Honda", :model => "Pilot")
		Automodels.create(:make => "Honda", :model => "Prelude")
		Automodels.create(:make => "Honda", :model => "Ridgeline")
		Automodels.create(:make => "Honda", :model => "S2000")
		Automodels.create(:make => "Hummer", :model => "H1")
		Automodels.create(:make => "Hummer", :model => "H2")
		Automodels.create(:make => "Hummer", :model => "H3")
		Automodels.create(:make => "Hummer", :model => "H3 SUV")
		Automodels.create(:make => "Hummer", :model => "H3T")
		Automodels.create(:make => "Hyundai", :model => "Accent")
		Automodels.create(:make => "Hyundai", :model => "Azera")
		Automodels.create(:make => "Hyundai", :model => "Elantra")
		Automodels.create(:make => "Hyundai", :model => "Entourage")
		Automodels.create(:make => "Hyundai", :model => "Genesis")
		Automodels.create(:make => "Hyundai", :model => "Genesis Coupe")
		Automodels.create(:make => "Hyundai", :model => "Santa Fe")
		Automodels.create(:make => "Hyundai", :model => "Sonata")
		Automodels.create(:make => "Hyundai", :model => "Tiburon")
		Automodels.create(:make => "Hyundai", :model => "Tucson")
		Automodels.create(:make => "Hyundai", :model => "Veracruz")
		Automodels.create(:make => "Hyundai", :model => "XG300")
		Automodels.create(:make => "Hyundai", :model => "XG350")
		Automodels.create(:make => "Infiniti", :model => "EX35")
		Automodels.create(:make => "Infiniti", :model => "FX35")
		Automodels.create(:make => "Infiniti", :model => "FX45")
		Automodels.create(:make => "Infiniti", :model => "FX50")
		Automodels.create(:make => "Infiniti", :model => "G20")
		Automodels.create(:make => "Infiniti", :model => "G35 Coupe")
		Automodels.create(:make => "Infiniti", :model => "G35 Sedan")
		Automodels.create(:make => "Infiniti", :model => "G37 Convertible")
		Automodels.create(:make => "Infiniti", :model => "G37 Coupe")
		Automodels.create(:make => "Infiniti", :model => "G37 Sedan")
		Automodels.create(:make => "Infiniti", :model => "I30")
		Automodels.create(:make => "Infiniti", :model => "I35")
		Automodels.create(:make => "Infiniti", :model => "J30")
		Automodels.create(:make => "Infiniti", :model => "M35")
		Automodels.create(:make => "Infiniti", :model => "M45")
		Automodels.create(:make => "Infiniti", :model => "Q45")
		Automodels.create(:make => "Infiniti", :model => "QX4")
		Automodels.create(:make => "Infiniti", :model => "QX56")
		Automodels.create(:make => "Isuzu", :model => "Amigo")
		Automodels.create(:make => "Isuzu", :model => "Ascender")
		Automodels.create(:make => "Isuzu", :model => "Axiom")
		Automodels.create(:make => "Isuzu", :model => "Hombre")
		Automodels.create(:make => "Isuzu", :model => "i-280")
		Automodels.create(:make => "Isuzu", :model => "i-290")
		Automodels.create(:make => "Isuzu", :model => "i-350")
		Automodels.create(:make => "Isuzu", :model => "i-370")
		Automodels.create(:make => "Isuzu", :model => "Oasis")
		Automodels.create(:make => "Isuzu", :model => "Rodeo")
		Automodels.create(:make => "Isuzu", :model => "Rodeo Sport")
		Automodels.create(:make => "Isuzu", :model => "Trooper")
		Automodels.create(:make => "Isuzu", :model => "VehiCROSS")
		Automodels.create(:make => "Jaguar", :model => "S-Type")
		Automodels.create(:make => "Jaguar", :model => "XF")
		Automodels.create(:make => "Jaguar", :model => "XJ")
		Automodels.create(:make => "Jaguar", :model => "XJ-Series")
		Automodels.create(:make => "Jaguar", :model => "XK")
		Automodels.create(:make => "Jaguar", :model => "XK-Series")
		Automodels.create(:make => "Jaguar", :model => "XK8")
		Automodels.create(:make => "Jaguar", :model => "X-Type")
		Automodels.create(:make => "Jeep", :model => "Cherokee")
		Automodels.create(:make => "Jeep", :model => "Cherokee RH Drive")
		Automodels.create(:make => "Jeep", :model => "Commander")
		Automodels.create(:make => "Jeep", :model => "Compass")
		Automodels.create(:make => "Jeep", :model => "Grand Cherokee")
		Automodels.create(:make => "Jeep", :model => "Liberty")
		Automodels.create(:make => "Jeep", :model => "Patriot")
		Automodels.create(:make => "Jeep", :model => "Wrangler")
		Automodels.create(:make => "Jeep", :model => "Wrangler Unlimited")
		Automodels.create(:make => "Kia", :model => "Amante")
		Automodels.create(:make => "Kia", :model => "Borrego")
		Automodels.create(:make => "Kia", :model => "Forte")
		Automodels.create(:make => "Kia", :model => "Optima")
		Automodels.create(:make => "Kia", :model => "Rio")
		Automodels.create(:make => "Kia", :model => "Rondo")
		Automodels.create(:make => "Kia", :model => "Sedona")
		Automodels.create(:make => "Kia", :model => "Sephia")
		Automodels.create(:make => "Kia", :model => "Sorento")
		Automodels.create(:make => "Kia", :model => "Soul")
		Automodels.create(:make => "Kia", :model => "Spectra")
		Automodels.create(:make => "Kia", :model => "Sportage")
		Automodels.create(:make => "Lamborghini", :model => "Gallardo")
		Automodels.create(:make => "Lamborghini", :model => "Murcielago")
		Automodels.create(:make => "Land Rover", :model => "Defender 90")
		Automodels.create(:make => "Land Rover", :model => "Discovery")
		Automodels.create(:make => "Land Rover", :model => "Discovery Series II")
		Automodels.create(:make => "Land Rover", :model => "Freelander")
		Automodels.create(:make => "Land Rover", :model => "LR2")
		Automodels.create(:make => "Land Rover", :model => "LR3")
		Automodels.create(:make => "Land Rover", :model => "Range Rover")
		Automodels.create(:make => "Land Rover", :model => "Range Rover Sport")
		Automodels.create(:make => "Lexus", :model => "ES 300")
		Automodels.create(:make => "Lexus", :model => "ES 300 Luxury Sports Sedan")
		Automodels.create(:make => "Lexus", :model => "ES 330")
		Automodels.create(:make => "Lexus", :model => "ES 350")
		Automodels.create(:make => "Lexus", :model => "GS 300")
		Automodels.create(:make => "Lexus", :model => "GS 300 Luxury Performance Sedan")
		Automodels.create(:make => "Lexus", :model => "GS 350")
		Automodels.create(:make => "Lexus", :model => "GS 400")
		Automodels.create(:make => "Lexus", :model => "GS 450 Luxury Performance Sedan")
		Automodels.create(:make => "Lexus", :model => "GS 430")
		Automodels.create(:make => "Lexus", :model => "GS 450h")
		Automodels.create(:make => "Lexus", :model => "GS 460")
		Automodels.create(:make => "Lexus", :model => "GX 470")
		Automodels.create(:make => "Lexus", :model => "HS 250h")
		Automodels.create(:make => "Lexus", :model => "IS 250")
		Automodels.create(:make => "Lexus", :model => "IS 250C")
		Automodels.create(:make => "Lexus", :model => "IS 300")
		Automodels.create(:make => "Lexus", :model => "IS 350")
		Automodels.create(:make => "Lexus", :model => "IS 350C")
		Automodels.create(:make => "Lexus", :model => "IS F")
		Automodels.create(:make => "Lexus", :model => "LS 400")
		Automodels.create(:make => "Lexus", :model => "LS 400 Luxury Sedan")
		Automodels.create(:make => "Lexus", :model => "LS 430")
		Automodels.create(:make => "Lexus", :model => "LS 460")
		Automodels.create(:make => "Lexus", :model => "LS 600h L")
		Automodels.create(:make => "Lexus", :model => "LX 450 Luxury Wagon")
		Automodels.create(:make => "Lexus", :model => "LX 470")
		Automodels.create(:make => "Lexus", :model => "LX 470 Luxury SUV")
		Automodels.create(:make => "Lexus", :model => "LX 470 Luxury Wagon")
		Automodels.create(:make => "Lexus", :model => "LX 570")
		Automodels.create(:make => "Lexus", :model => "RX 300")
		Automodels.create(:make => "Lexus", :model => "RX 300 Luxury SUV")
		Automodels.create(:make => "Lexus", :model => "RX 330")
		Automodels.create(:make => "Lexus", :model => "RX 350")
		Automodels.create(:make => "Lexus", :model => "RX 400h")
		Automodels.create(:make => "Lexus", :model => "RX 450h")
		Automodels.create(:make => "Lexus", :model => "SC 300")
		Automodels.create(:make => "Lexus", :model => "SC 300 Luxury Sports Coupe")
		Automodels.create(:make => "Lexus", :model => "SC 400")
		Automodels.create(:make => "Lexus", :model => "SC 400 Luxury Sports Coupe")
		Automodels.create(:make => "Lexus", :model => "SC 430")
		Automodels.create(:make => "Lincoln", :model => "Aviator")
		Automodels.create(:make => "Lincoln", :model => "Blackwood")
		Automodels.create(:make => "Lincoln", :model => "Continental")
		Automodels.create(:make => "Lincoln", :model => "LS")
		Automodels.create(:make => "Lincoln", :model => "Mark LT")
		Automodels.create(:make => "Lincoln", :model => "Mark VIII")
		Automodels.create(:make => "Lincoln", :model => "MKS")
		Automodels.create(:make => "Lincoln", :model => "MKT")
		Automodels.create(:make => "Lincoln", :model => "MKX")
		Automodels.create(:make => "Lincoln", :model => "MKZ")
		Automodels.create(:make => "Lincoln", :model => "Navigator")
		Automodels.create(:make => "Lincoln", :model => "Navigator L")
		Automodels.create(:make => "Lincoln", :model => "Town Car")
		Automodels.create(:make => "Lincoln", :model => "Zephyr")
		Automodels.create(:make => "Lotus", :model => "Elise")
		Automodels.create(:make => "Lotus", :model => "Esprit")
		Automodels.create(:make => "Lotus", :model => "Evora")
		Automodels.create(:make => "Lotus", :model => "Exige")
		Automodels.create(:make => "Maserati", :model => "Coupe")
		Automodels.create(:make => "Maserati", :model => "GranSport")
		Automodels.create(:make => "Maserati", :model => "GranTurismo")
		Automodels.create(:make => "Maserati", :model => "Quattroporte")
		Automodels.create(:make => "Maserati", :model => "Spyder")
		Automodels.create(:make => "Maybach", :model => "57")
		Automodels.create(:make => "Maybach", :model => "57s")
		Automodels.create(:make => "Maybach", :model => "62")
		Automodels.create(:make => "Maybach", :model => "62s")
		Automodels.create(:make => "Maybach", :model => "Landaulet")
		Automodels.create(:make => "Mazda", :model => "626")
		Automodels.create(:make => "Mazda", :model => "B2300")
		Automodels.create(:make => "Mazda", :model => "B2500")
		Automodels.create(:make => "Mazda", :model => "B3000")
		Automodels.create(:make => "Mazda", :model => "B4000")
		Automodels.create(:make => "Mazda", :model => "CX-7")
		Automodels.create(:make => "Mazda", :model => "CX-9")
		Automodels.create(:make => "Mazda", :model => "Mazda3")
		Automodels.create(:make => "Mazda", :model => "Mazda5")
		Automodels.create(:make => "Mazda", :model => "Mazda6")
		Automodels.create(:make => "Mazda", :model => "Millenia")
		Automodels.create(:make => "Mazda", :model => "MPV")
		Automodels.create(:make => "Mazda", :model => "MX-5 Miata")
		Automodels.create(:make => "Mazda", :model => "MX6")
		Automodels.create(:make => "Mazda", :model => "Protégé")
		Automodels.create(:make => "Mazda", :model => "Protege5")
		Automodels.create(:make => "Mazda", :model => "RX-8")
		Automodels.create(:make => "Mazda", :model => "Tribute")
		Automodels.create(:make => "Mercedes-Benz", :model => "C-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "CL-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "CLK-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "CLS-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "E-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "G-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "GL-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "GLK-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "M-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "R-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "S-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "SL-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "SLK-Class")
		Automodels.create(:make => "Mercedes-Benz", :model => "SLR McLaren")
		Automodels.create(:make => "Mercury", :model => "Cougar")
		Automodels.create(:make => "Mercury", :model => "Grand Marquis")
		Automodels.create(:make => "Mercury", :model => "Marauder")
		Automodels.create(:make => "Mercury", :model => "Meriner")
		Automodels.create(:make => "Mercury", :model => "Milan")
		Automodels.create(:make => "Mercury", :model => "Montego")
		Automodels.create(:make => "Mercury", :model => "Monterey")
		Automodels.create(:make => "Mercury", :model => "Mountaineer")
		Automodels.create(:make => "Mercury", :model => "Mystique")
		Automodels.create(:make => "Mercury", :model => "Sable")
		Automodels.create(:make => "Mercury", :model => "Tracer")
		Automodels.create(:make => "Mercury", :model => "Villager")
		Automodels.create(:make => "Mercury", :model => "Villager Wagon")
		Automodels.create(:make => "Mini", :model => "Cooper Clubman")
		Automodels.create(:make => "Mini", :model => "Cooper Convertible")
		Automodels.create(:make => "Mini", :model => "Cooper Hardtop")
		Automodels.create(:make => "Mitsubishi", :model => "3000GT")
		Automodels.create(:make => "Mitsubishi", :model => "Diamante")
		Automodels.create(:make => "Mitsubishi", :model => "Eclipse")
		Automodels.create(:make => "Mitsubishi", :model => "Endeavor")
		Automodels.create(:make => "Mitsubishi", :model => "Galant")
		Automodels.create(:make => "Mitsubishi", :model => "Lancer")
		Automodels.create(:make => "Mitsubishi", :model => "Mirage")
		Automodels.create(:make => "Mitsubishi", :model => "Montero")
		Automodels.create(:make => "Mitsubishi", :model => "Montero Sport")
		Automodels.create(:make => "Mitsubishi", :model => "Outlander")
		Automodels.create(:make => "Mitsubishi", :model => "Raider")
		Automodels.create(:make => "Nissan", :model => "200SX")
		Automodels.create(:make => "Nissan", :model => "240SX")
		Automodels.create(:make => "Nissan", :model => "350Z")
		Automodels.create(:make => "Nissan", :model => "370Z")
		Automodels.create(:make => "Nissan", :model => "Altima")
		Automodels.create(:make => "Nissan", :model => "Armada")
		Automodels.create(:make => "Nissan", :model => "Cube")
		Automodels.create(:make => "Nissan", :model => "Frontier")
		Automodels.create(:make => "Nissan", :model => "GT-R")
		Automodels.create(:make => "Nissan", :model => "Maxima")
		Automodels.create(:make => "Nissan", :model => "Murano")
		Automodels.create(:make => "Nissan", :model => "Pathfinder")
		Automodels.create(:make => "Nissan", :model => "Pathfinder Armada")
		Automodels.create(:make => "Nissan", :model => "Quest")
		Automodels.create(:make => "Nissan", :model => "Rogue")
		Automodels.create(:make => "Nissan", :model => "Sentra")
		Automodels.create(:make => "Nissan", :model => "Titan")
		Automodels.create(:make => "Nissan", :model => "Trucks 2WD")
		Automodels.create(:make => "Nissan", :model => "Trucks 4WD")
		Automodels.create(:make => "Nissan", :model => "Versa")
		Automodels.create(:make => "Nissan", :model => "Xterra")
		Automodels.create(:make => "Oldsmobile", :model => "88")
		Automodels.create(:make => "Oldsmobile", :model => "Achieva")
		Automodels.create(:make => "Oldsmobile", :model => "Alero")
		Automodels.create(:make => "Oldsmobile", :model => "Aurora")
		Automodels.create(:make => "Oldsmobile", :model => "Bravada")
		Automodels.create(:make => "Oldsmobile", :model => "Cutlass")
		Automodels.create(:make => "Oldsmobile", :model => "Cutlass Supreme")
		Automodels.create(:make => "Oldsmobile", :model => "Intrigue")
		Automodels.create(:make => "Oldsmobile", :model => "LSS")
		Automodels.create(:make => "Oldsmobile", :model => "Regency")
		Automodels.create(:make => "Oldsmobile", :model => "Silhouette")
		Automodels.create(:make => "Panoz", :model => "Esperante")
		Automodels.create(:make => "Plymouth", :model => "Breeze")
		Automodels.create(:make => "Plymouth", :model => "Grand Voyager")
		Automodels.create(:make => "Plymouth", :model => "Neon")
		Automodels.create(:make => "Plymouth", :model => "Prowler")
		Automodels.create(:make => "Plymouth", :model => "Voyager")
		Automodels.create(:make => "Pontiac", :model => "Aztec")
		Automodels.create(:make => "Pontiac", :model => "Bonneville")
		Automodels.create(:make => "Pontiac", :model => "Firebird")
		Automodels.create(:make => "Pontiac", :model => "G3")
		Automodels.create(:make => "Pontiac", :model => "G5")
		Automodels.create(:make => "Pontiac", :model => "G6")
		Automodels.create(:make => "Pontiac", :model => "G8")
		Automodels.create(:make => "Pontiac", :model => "Grand Am")
		Automodels.create(:make => "Pontiac", :model => "Grand Prix")
		Automodels.create(:make => "Pontiac", :model => "GTO")
		Automodels.create(:make => "Pontiac", :model => "Montana")
		Automodels.create(:make => "Pontiac", :model => "Montana SV6")
		Automodels.create(:make => "Pontiac", :model => "Solstice")
		Automodels.create(:make => "Pontiac", :model => "Sunfire")
		Automodels.create(:make => "Pontiac", :model => "Torrent")
		Automodels.create(:make => "Pontiac", :model => "Trans Sport")
		Automodels.create(:make => "Pontiac", :model => "Vibe")
		Automodels.create(:make => "Porsche", :model => "911 Carrera")
		Automodels.create(:make => "Porsche", :model => "911 Carrera 4")
		Automodels.create(:make => "Porsche", :model => "Boxster")
		Automodels.create(:make => "Porsche", :model => "Carrera GT")
		Automodels.create(:make => "Porsche", :model => "Cayenne")
		Automodels.create(:make => "Porsche", :model => "Cayman")
		Automodels.create(:make => "Porsche", :model => "Panamera")
		Automodels.create(:make => "Rolls-Royce", :model => "Corniche")
		Automodels.create(:make => "Rolls-Royce", :model => "Park Ward")
		Automodels.create(:make => "Rolls-Royce", :model => "Phantom")
		Automodels.create(:make => "Rolls-Royce", :model => "Phantom Coupe")
		Automodels.create(:make => "Rolls-Royce", :model => "Phantom Drophead Coupe")
		Automodels.create(:make => "Rolls-Royce", :model => "Silver Seraph")
		Automodels.create(:make => "Saab", :model => "900")
		Automodels.create(:make => "Saab", :model => "9000")
		Automodels.create(:make => "Saab", :model => "9-2X")
		Automodels.create(:make => "Saab", :model => "9-3")
		Automodels.create(:make => "Saab", :model => "9-5")
		Automodels.create(:make => "Saab", :model => "9-7X")
		Automodels.create(:make => "Saturn", :model => "Astra")
		Automodels.create(:make => "Saturn", :model => "Aura")
		Automodels.create(:make => "Saturn", :model => "Aura Hybrid")
		Automodels.create(:make => "Saturn", :model => "Ion")
		Automodels.create(:make => "Saturn", :model => "LS")
		Automodels.create(:make => "Saturn", :model => "L-Series")
		Automodels.create(:make => "Saturn", :model => "LW")
		Automodels.create(:make => "Saturn", :model => "Outlook")
		Automodels.create(:make => "Saturn", :model => "Relay")
		Automodels.create(:make => "Saturn", :model => "SC 2dr")
		Automodels.create(:make => "Saturn", :model => "SC 3dr")
		Automodels.create(:make => "Saturn", :model => "Sky")
		Automodels.create(:make => "Saturn", :model => "SL")
		Automodels.create(:make => "Saturn", :model => "SW")
		Automodels.create(:make => "Saturn", :model => "SW RHD")
		Automodels.create(:make => "Saturn", :model => "Vue")
		Automodels.create(:make => "Saturn", :model => "Vue Hybrid")
		Automodels.create(:make => "Scion", :model => "tC")
		Automodels.create(:make => "Scion", :model => "xA")
		Automodels.create(:make => "Scion", :model => "xB")
		Automodels.create(:make => "Scion", :model => "xD")
		Automodels.create(:make => "Smart", :model => "fortwo")
		Automodels.create(:make => "Subaru", :model => "B9 Tribeca")
		Automodels.create(:make => "Subaru", :model => "Baja")
		Automodels.create(:make => "Subaru", :model => "Forester")
		Automodels.create(:make => "Subaru", :model => "Impreza")
		Automodels.create(:make => "Subaru", :model => "Impreza Coupe")
		Automodels.create(:make => "Subaru", :model => "Impreza Sedan")
		Automodels.create(:make => "Subaru", :model => "Impreza Wagon")
		Automodels.create(:make => "Subaru", :model => "Impreza WRX")
		Automodels.create(:make => "Subaru", :model => "Legacy")
		Automodels.create(:make => "Subaru", :model => "Legacy Sedan")
		Automodels.create(:make => "Subaru", :model => "Legacy Wagon")
		Automodels.create(:make => "Subaru", :model => "Outback")
		Automodels.create(:make => "Subaru", :model => "SVX")
		Automodels.create(:make => "Subaru", :model => "Tribeca")
		Automodels.create(:make => "Suzuki", :model => "Aerio")
		Automodels.create(:make => "Suzuki", :model => "Equator")
		Automodels.create(:make => "Suzuki", :model => "Esteem")
		Automodels.create(:make => "Suzuki", :model => "Forenza")
		Automodels.create(:make => "Suzuki", :model => "Grand Vitara")
		Automodels.create(:make => "Suzuki", :model => "Reno")
		Automodels.create(:make => "Suzuki", :model => "Sidekick")
		Automodels.create(:make => "Suzuki", :model => "Swift")
		Automodels.create(:make => "Suzuki", :model => "SX4")
		Automodels.create(:make => "Suzuki", :model => "Verona")
		Automodels.create(:make => "Suzuki", :model => "Vitara")
		Automodels.create(:make => "Suzuki", :model => "X-90")
		Automodels.create(:make => "Suzuki", :model => "XL-7")
		Automodels.create(:make => "Tesla", :model => "Roadster")
		Automodels.create(:make => "Toyota", :model => "4Runner")
		Automodels.create(:make => "Toyota", :model => "Avalon")
		Automodels.create(:make => "Toyota", :model => "Camry")
		Automodels.create(:make => "Toyota", :model => "Camry Hybrid")
		Automodels.create(:make => "Toyota", :model => "Camry Solara")
		Automodels.create(:make => "Toyota", :model => "Celica")
		Automodels.create(:make => "Toyota", :model => "Corolla")
		Automodels.create(:make => "Toyota", :model => "Echo")
		Automodels.create(:make => "Toyota", :model => "FJ Cruiser")
		Automodels.create(:make => "Toyota", :model => "Highlander")
		Automodels.create(:make => "Toyota", :model => "Highlander Hybrid")
		Automodels.create(:make => "Toyota", :model => "Land Cruiser")
		Automodels.create(:make => "Toyota", :model => "Matrix")
		Automodels.create(:make => "Toyota", :model => "MR2 Spyder")
		Automodels.create(:make => "Toyota", :model => "Paseo")
		Automodels.create(:make => "Toyota", :model => "Previa")
		Automodels.create(:make => "Toyota", :model => "Prius")
		Automodels.create(:make => "Toyota", :model => "RAV4")
		Automodels.create(:make => "Toyota", :model => "Sequoia")
		Automodels.create(:make => "Toyota", :model => "Sienna")
		Automodels.create(:make => "Toyota", :model => "Supra")
		Automodels.create(:make => "Toyota", :model => "T100")
		Automodels.create(:make => "Toyota", :model => "Tacoma")
		Automodels.create(:make => "Toyota", :model => "Tercel")
		Automodels.create(:make => "Toyota", :model => "Tundra")
		Automodels.create(:make => "Toyota", :model => "Venza")
		Automodels.create(:make => "Toyota", :model => "Yaris")
		Automodels.create(:make => "Volkswagen", :model => "Beetle")
		Automodels.create(:make => "Volkswagen", :model => "Beetle Convertible")
		Automodels.create(:make => "Volkswagen", :model => "Beetle Coupe")
		Automodels.create(:make => "Volkswagen", :model => "Cabrio")
		Automodels.create(:make => "Volkswagen", :model => "CC")
		Automodels.create(:make => "Volkswagen", :model => "Eos")
		Automodels.create(:make => "Volkswagen", :model => "EuroVan")
		Automodels.create(:make => "Volkswagen", :model => "GLI")
		Automodels.create(:make => "Volkswagen", :model => "Golf")
		Automodels.create(:make => "Volkswagen", :model => "GTI")
		Automodels.create(:make => "Volkswagen", :model => "Jetta")
		Automodels.create(:make => "Volkswagen", :model => "Jetta Sedan")
		Automodels.create(:make => "Volkswagen", :model => "Jetta Sedan A5")
		Automodels.create(:make => "Volkswagen", :model => "Jetta SportWagen")
		Automodels.create(:make => "Volkswagen", :model => "Jetta Wagon")
		Automodels.create(:make => "Volkswagen", :model => "Passat")
		Automodels.create(:make => "Volkswagen", :model => "Passat Sedan")
		Automodels.create(:make => "Volkswagen", :model => "Passat Wagon")
		Automodels.create(:make => "Volkswagen", :model => "Phaeton")
		Automodels.create(:make => "Volkswagen", :model => "R32")
		Automodels.create(:make => "Volkswagen", :model => "Rabbit")
		Automodels.create(:make => "Volkswagen", :model => "Routan")
		Automodels.create(:make => "Volkswagen", :model => "Tiguan")
		Automodels.create(:make => "Volkswagen", :model => "Touareg")
		Automodels.create(:make => "Volkswagen", :model => "Touareg 2")
		Automodels.create(:make => "Volvo", :model => "850")
		Automodels.create(:make => "Volvo", :model => "960")
		Automodels.create(:make => "Volvo", :model => "C30")
		Automodels.create(:make => "Volvo", :model => "C70")
		Automodels.create(:make => "Volvo", :model => "S40")
		Automodels.create(:make => "Volvo", :model => "S60")
		Automodels.create(:make => "Volvo", :model => "S70")
		Automodels.create(:make => "Volvo", :model => "S80")
		Automodels.create(:make => "Volvo", :model => "S90")
		Automodels.create(:make => "Volvo", :model => "V40")
		Automodels.create(:make => "Volvo", :model => "V50")
		Automodels.create(:make => "Volvo", :model => "V70")
		Automodels.create(:make => "Volvo", :model => "V90")
		Automodels.create(:make => "Volvo", :model => "XC60")
		Automodels.create(:make => "Volvo", :model => "XC70")
		Automodels.create(:make => "Volvo", :model => "XC90")
  end

  def self.down
  	Automodels.destroy_all
  end
end
