class AddOtherToAutomodels < ActiveRecord::Migration
  def self.up
  	Automodels.create(:make => 'Acura', :model => 'Other')
		Automodels.create(:make => 'Aston Martin', :model => 'Other')
		Automodels.create(:make => 'Audi', :model => 'Other')
		Automodels.create(:make => 'Bentley', :model => 'Other')
		Automodels.create(:make => 'BMW            ', :model => 'Other')
		Automodels.create(:make => 'Buick', :model => 'Other')
		Automodels.create(:make => 'Cadillac', :model => 'Other')
		Automodels.create(:make => 'Chevrolet      ', :model => 'Other')
		Automodels.create(:make => 'Chrysler', :model => 'Other')
		Automodels.create(:make => 'Daewoo', :model => 'Other')
		Automodels.create(:make => 'Dodge', :model => 'Other')
		Automodels.create(:make => 'Eagle', :model => 'Other')
		Automodels.create(:make => 'Ferrari', :model => 'Other')
		Automodels.create(:make => 'Ford', :model => 'Other')
		Automodels.create(:make => 'Geo', :model => 'Other')
		Automodels.create(:make => 'GMC', :model => 'Other')
		Automodels.create(:make => 'Honda', :model => 'Other')
		Automodels.create(:make => 'Hummer', :model => 'Other')
		Automodels.create(:make => 'Hyundai', :model => 'Other')
		Automodels.create(:make => 'Infiniti', :model => 'Other')
		Automodels.create(:make => 'Isuzu', :model => 'Other')
		Automodels.create(:make => 'Jaguar', :model => 'Other')
		Automodels.create(:make => 'Jeep', :model => 'Other')
		Automodels.create(:make => 'Kia', :model => 'Other')
		Automodels.create(:make => 'Lamborghini', :model => 'Other')
		Automodels.create(:make => 'Land Rover', :model => 'Other')
		Automodels.create(:make => 'Lexus', :model => 'Other')
		Automodels.create(:make => 'Lincoln', :model => 'Other')
		Automodels.create(:make => 'Lotus', :model => 'Other')
		Automodels.create(:make => 'Maserati', :model => 'Other')
		Automodels.create(:make => 'Maybach', :model => 'Other')
		Automodels.create(:make => 'Mazda', :model => 'Other')
		Automodels.create(:make => 'Mercedes-Benz', :model => 'Other')
		Automodels.create(:make => 'Mercury', :model => 'Other')
		Automodels.create(:make => 'Mini', :model => 'Other')
		Automodels.create(:make => 'Mitsubishi', :model => 'Other')
		Automodels.create(:make => 'Nissan', :model => 'Other')
		Automodels.create(:make => 'Oldsmobile', :model => 'Other')
		Automodels.create(:make => 'Other', :model => 'Other')
		Automodels.create(:make => 'Panoz', :model => 'Other')
		Automodels.create(:make => 'Plymouth', :model => 'Other')
		Automodels.create(:make => 'Pontiac', :model => 'Other')
		Automodels.create(:make => 'Porsche', :model => 'Other')
		Automodels.create(:make => 'Rolls-Royce', :model => 'Other')
		Automodels.create(:make => 'Saab', :model => 'Other')
		Automodels.create(:make => 'Saturn', :model => 'Other')
		Automodels.create(:make => 'Scion', :model => 'Other')
		Automodels.create(:make => 'Smart', :model => 'Other')
		Automodels.create(:make => 'Subaru', :model => 'Other')
		Automodels.create(:make => 'Suzuki', :model => 'Other')
		Automodels.create(:make => 'Tesla', :model => 'Other')
		Automodels.create(:make => 'Toyota', :model => 'Other')
		Automodels.create(:make => 'Volkswagen', :model => 'Other')
		Automodels.create(:make => 'Volvo', :model => 'Other')
  end

  def self.down
  end
end
